export {default as Search} from './Search'
export {default as Card} from './card/Card'
export {default as Skeletoncard} from './card/Skeletoncard'
export {default as ImageMagnifier} from './Magnify'
export {default as MainModal} from './MainModal'
